### PR TITLE
import_multisig_info: fix sanity check crash in detach_blockchain

### LINKED ISSUE #3505: Unable to make import_multisig_info: Daemon claims reorg below last checkpoint
I'm playing around with monero multisignatures and encountered the error in current master:
```
[wallet 49yJuz]: export_multisig_info info1
Wallet password: 
File info1 already exists. Are you sure to overwrite it? (Y/Yes/N/No): y
Multisig info exported to info1
[wallet 49yJuz]: import_multisig_info info2 info3
Wallet password: 
Error: Failed to import multisig info: Daemon claims reorg below last checkpoint
[wallet 49yJuz]: 
```
This happens because wallet wants to `detach_blockchain` on height where the first multisignture output is met (which is 1520XXX), but there is new checkpoint on height 1530000 so sanity check inside the function throws the error.

### PR DESCRIPTION
**Pull request by mmitkevich**
This fixes #3505. Tested on OSX 13.12

### CODE REVIEW

File: src/wallet/wallet2.cpp [hunk 1]
```diff
@@ -2413,17 +2413,22 @@ bool wallet2::get_output_distribution(uint64_t &start_height, std::vector<uint64
...
   // size  1 2 3 4 5 6 7 8 9
   // block 0 1 2 3 4 5 6 7 8
   //               C
   THROW_WALLET_EXCEPTION_IF(height <= m_checkpoints.get_max_height() && m_blockchain.size() > m_checkpoints.get_max_height(),
       error::wallet_internal_error, "Daemon claims reorg below last checkpoint");
 
+  detach_blockchain_unsafe(height);
+}
+//----------------------------------------------------------------------------------------------------
+void wallet2::detach_blockchain_unsafe(uint64_t height)
```
Comment (jtgrassie) [inline src/wallet/wallet2.cpp]: Why the need for a new function?

File: src/wallet/wallet2.h [hunk 2]
```diff
@@ -1093,6 +1093,9 @@ namespace tools
     void process_new_transaction(const crypto::hash &txid, const cryptonote::transaction& tx, const std::vector<uint64_t> &o_indices, uint64_t height, uint64_t ts, bool miner_tx, bool pool, bool double_spend_seen);
     void process_new_blockchain_entry(const cryptonote::block& b, const cryptonote::block_complete_entry& bche, const crypto::hash& bl_id, uint64_t height, const cryptonote::COMMAND_RPC_GET_BLOCKS_FAST::block_output_indices &o_indices);
     void detach_blockchain(uint64_t height);
+    
+    void detach_blockchain_unsafe(uint64_t height);
```
Comment (jtgrassie) [inline src/wallet/wallet2.h]: Why the need for a new function? Plus, why all the added whitespace?

Comment (mmitkevich) [reply src/wallet/wallet2.h]: - when detach_blockchain is called while replaying new blocks, checkpoints sanity check is required. 
- when detach_blockchain is called from import_multisig_info checkpoints sanity check is superfluous, because some multisig transactions could be before checkpoint. So unsafe version is called

Comment (jtgrassie) [reply src/wallet/wallet2.h]: But `detach_blockchain` is now just calling `detach_blockchain_unssafe`, which is just a slightly modified version of the previous `detach_blockchain`. Why not just make the change to the original function thus negating the need for an extra call?

Comment (mmitkevich) [reply src/wallet/wallet2.h]: That could be converted in the bool flag, but I decided that additional flags is more ugly than `_unsafe` version. 

I assume we cannot just remove `THROW_WALLET_EXCEPTION_IF` because we're required to verify checkpoints when downloading new blocks. 

But in `import_multisig_info` case this condition could be violated and so I try to avoid it specially for this case only.

Comment (jtgrassie) [reply src/wallet/wallet2.h]: Thing is, you should still would want a check, hence why it would be better to edit the exception logic IMO. At the end of the day, you don't want to detach at a bad height.

File: src/wallet/wallet2.cpp [hunk 3]
```diff
@@ -2413,17 +2413,22 @@ bool wallet2::get_output_distribution(uint64_t &start_height, std::vector<uint64
   distribution = std::move(res.distributions[0].distribution);
   return true;
 }
-//----------------------------------------------------------------------------------------------------
-void wallet2::detach_blockchain(uint64_t height)
-{
-  LOG_PRINT_L0("Detaching blockchain on height " << height);
+
+void wallet2::detach_blockchain(uint64_t height) {
+    LOG_PRINT_L0("Detaching blockchain on height " << height);
```
Comment (moneromooo-monero) [inline src/wallet/wallet2.cpp]: No random reformatting please.

**Comment by mmitkevich** [comment]
fixed whitespaces.

**Comment by stoffu** [comment]
I still see the unwanted reformatting that should go away:
```diff
-void wallet2::detach_blockchain(uint64_t height)
-{
-  LOG_PRINT_L0("Detaching blockchain on height " << height);
+void wallet2::detach_blockchain(uint64_t height) {
+    LOG_PRINT_L0("Detaching blockchain on height " << height);
```

**Comment by mmitkevich** [comment]
@stoffu I hope I fixed it finally.

**Comment by moneromooo-monero** [comment]
I found what was bothering me with this: the assert should be changed to use the hashchain offet, rather than the last checkpoint. These were equal before the change to clamp the trim height. Then you should not need to split.

**Comment by moneromooo-monero** [comment]
Yes. Do you agree with the change ?

**Comment by mmitkevich** [comment]
I will test your solution and return with updated PR if everything would be fine.

**Comment by mmitkevich** [comment]
@moneromooo-monero , I tested it worked OK in  my `import_multisig_info` scenario.

I changed to strong inequality `height < m_blockchain.offset()` though.

No additional methods now. Please, review.
