### PR TITLE
Fixed Keccak implementation on big-endian platforms

### LINKED ISSUE #4392: Wrong hashes produced by Keccak1600 implementation on big-endian platforms
Issue is pretty much self-explanatory. The most likely culprit are unsafe pointer type casts, that appear in the implementation [`src/crypto/keccak.c`](https://github.com/monero-project/monero/blob/master/src/crypto/keccak.c). E.g.:

https://github.com/monero-project/monero/blob/master/src/crypto/keccak.c#L108
https://github.com/monero-project/monero/blob/master/src/crypto/keccak.c#L124

## Proof-of-concept
```c
int main()
{
    uint8_t hash[200];
    keccak1600("", 0, hash);
    hexdump(hash, 200);
    return 0;
}
```

Expected result (output on my x86 computer):
```
C5D2460186F7233C927E7DB2DCC703C0E500B653CA82273B7BFAD8045D85A4703DBB9A2CD87CA974B9A2B0EC61119BCB5CEDF9C0C411221F6141A25F17C60D82D24680ABBCBFBA815B762B24B751D5B1E85325BA5E6DF23C10725BFE986ACE3BA2D24535A79F7DBABB153BB0D33C0DFA09CEC712EBD7FE3B49A9194E859C82EBFF11A645651A5D1B726BE100F44641069FAB7164E13487FE3609BBEEBD88309CBAACB2A7ECB8E8DE2145CF1DB7623B16916D7210991B576BBE182362CF22FAB7D7AF9F77F71AFEA3
```
Output on big-endian machines:
```
4A3D5976EDD24A1A22F7FAE2985B3BD41798EB1176802B50E5612F3E739D3C97FD3980B0DDE09F15F7B03912A94091D65666F12BE92101C5D5473A2AAEF0715B1B8557865FEFC35FAF881B6130248A82657828CE691B6735E444A21B7E4FFD8E348AA2FCB438DF080DD77CEB98D486D2CB97A1C48152F1E5E0EB69D0C38305812883C1C67718879F81A607A48B12EBFD7AF50944B97FDD4C9C46C0CB353EA8C19F307B56FFA4EF8C1D8B7E9086C977E5C517A7AEA67EF838C925E9497A50DACBB6FC06228EBC4523
```

### PR DESCRIPTION
**Pull request by AlexAltea**
Fixes #4392.

### CODE REVIEW

File: src/crypto/keccak.c [hunk 1]
```diff
@@ -121,11 +122,11 @@ void keccak(const uint8_t *in, size_t inlen, uint8_t *md, int mdlen)
     temp[rsiz - 1] |= 0x80;
 
     for (i = 0; i < rsizw; i++)
-        st[i] ^= ((uint64_t *) temp)[i];
+        st[i] ^= swap64le(((uint64_t *) temp)[i]);
 
     keccakf(st, KECCAK_ROUNDS);
 
-    memcpy(md, st, mdlen);
+    memcpy_swap64le(md, st, mdlen);
```
Comment (moneromooo-monero) [inline src/crypto/keccak.c]: This should check that mdlen is a multiple of sizeof(uint64_t) and call memcpy_swap64le with mdlen/sizeof(uint64_t).

**Comment by AlexAltea** [comment]
@moneromooo-monero Good point, thank you. I've fixed the `memcpy_swap64le` call.

> This should check that mdlen is a multiple of sizeof(uint64_t)

At the beginning of the function we already make sure that `sizeof(st) == (size_t)mdlen`. This implies that `mdlen` is a multiple of `sizeof(uint64_t)` so there's no need of adding another check.

**Comment by moneromooo-monero** [comment]
I almost OK'd it, but then I went to double check, and there is no such test (not in all cases anyway).
