### PR TITLE
initialize timestamp to 0 and check for mktime() error

### LINKED ISSUE #1551: Unable to see any transactions with wallets generated from keys on macOS
On macOS Sierra 10.12, I am unable to see any transactions in the CLI or GUI for wallets that were created using `--generate-from-keys`. This causes the balance to always be 0.

With `set_log 2`, I am able to see that during the blockchain scan, every block is skipped due to the account timestamp being incorrect:

>Skipped block by timestamp, height: 1220200, block time 1483989027, account time 18446744073709551615

### PR DESCRIPTION
**Pull request by vickio**
This fixes #1551, where a bad account creation timestamp was causing transactions to not load in the CLI.

The problem was that on some systems, uninitialized variables in the `tm` struct were causing `mktime()` to return `-1` in `account_base::create_from_keys()`. This is what was being passed to `mktime()`:

    (tm) $0 = {
      tm_sec = 0
      tm_min = 0
      tm_hour = 0
      tm_mday = 15
      tm_mon = 3
      tm_year = 114
      tm_wday = 1606389616
      tm_yday = 32767
      tm_isdst = 1
      tm_gmtoff = 140734799777680
      tm_zone = 0x00007fff5fbf9778 "\x12test.keys"
    }

Initializing the struct to 0 before using fixes it. I also added a check to make sure errors from `mktime()` work predictably by setting `m_creation_timestamp` to 0 (epoch).

### CODE REVIEW

File: src/cryptonote_core/account.cpp [hunk 1]
```diff
@@ -97,15 +97,15 @@ DISABLE_VS_WARNINGS(4244 4345)
...
+    struct tm timestamp = {0};
     timestamp.tm_year = 2014 - 1900;  // year 2014
     timestamp.tm_mon = 4 - 1;  // month april
     timestamp.tm_mday = 15;  // 15th of april
     timestamp.tm_hour = 0;
     timestamp.tm_min = 0;
     timestamp.tm_sec = 0;
 
-    m_creation_timestamp = mktime(&timestamp);
+    m_creation_timestamp = std::max(mktime(&timestamp), (long)0);
```
Comment (NanoAkron) [inline src/cryptonote_core/account.cpp]: Is long big enough or are we using 64-bit time stamps?

**Comment by moneromooo-monero** [comment]
ok (though the max call is maybe a bit confusing, but that works)

**Comment by moneromooo-monero** [comment]
The max thing actually broke on win64. Can you check whether https://github.com/monero-project/monero/pull/1566 actually still works for you ?
