### PR TITLE
Check for windows NTFS compression on monerod startup (fixes #9617)

### LINKED ISSUE #9617: Windows NTFS compression causes crash during sync
As reported here https://github.com/monero-project/monero/issues/9569#issuecomment-2539368523

It would be good to add a check to monerod to make sure the Windows file system, or the lmdb database does not have automatic compression enabled, otherwise it seems to crash during sync.

### PR DESCRIPTION
**Pull request by eversinc33**
Fixes #9617

If the data-dir is compressed and the lmdb folder is (check for both, because if data-dir is compressed and lmdb doesnt exist yet, it is likely that the compression is configured to be applied recursively):

image

If just the db folder is compressed:

image

If not compressed at all:

image

Just logging an ERROR message, just like if Fat32 is used, not aborting, because for a small blockchain this not be a critical issue. 

Can we assume that "lmdb" stays the name of the db folder? Since it is hardcoded here. Otherwise, one would need to define it somewhere central. I assumed so, because `BlockchainLMDB::get_db_name()` also has it hardcoded.

### CODE REVIEW

**Comment by nahuhh** [comment]
Should probably only need to check the `data-dir/lmdb`

example `.bitmonero/lmdb`.

> Can we assume that "lmdb" stays the name of the db folder?

Testnet & stagenet will end up in subfolders like `.bitmonero/testnet/lmdb`

**Comment by eversinc33** [comment]
> Should probably only need to check the `data-dir/lmdb`

If there is no edge case where data-dir` is created, but `lmdb` isnt yet, sure.

> Testnet & stagenet will end up in subfolders like `.bitmonero/testnet/lmdb`

That is taken care of with `data_dir / "lmdb"`

**Comment by eversinc33** [comment]
Changed so that only the database directory is checked, and if it doesnt exist, it falls back to checking the data-dir.

**Comment by iamamyth** [comment]
Either the software supports a compressed database/data dir, or it doesn't (I'm not certain as to the policy here, though compression + memory mapping seems like a bad idea); logging an ERROR and proceeding with startup doesn't make sense to me, and doesn't "fix" much of anything.

**Comment by eversinc33** [comment]
My reasoning was that this error only seems to become a problem if the blockchain exceeds 70GB (see https://github.com/monero-project/monero/issues/9569#issuecomment-2539368523), so its not a reason to halt if e.g. running for a smaller chain such as the testnet (or if the on disk chain becomes smaller in the future due to e.g. further pruning improvements). Im very open to discussions as I am just getting familiar with the codebase.

**Comment by iamamyth** [comment]
I think you're on the right track here, but, conceptually, the blockchain grows forever, so allowing startup in a configuration which will eventually break wastes the feature detection and proves quite irritating for users (mainnet is the most critical use case and it exceeds the failure threshold). I may have uncovered the underlying problem: "If you compress a file that is larger than 30 gigabytes, the compression may not succeed." (https://learn.microsoft.com/en-us/windows/win32/fileio/file-compression-and-decompression). Rather than simply warning the user, or aborting, I suggest transparently fixing the problem in the BlockchainLMDB class:

1. When creating the data directory in `open`, disable compression on the directory.
2. (Maybe) If the db file exists and is compressed, prior to mdb_env_open, disable compression on the db file. This would fix existing databases going forward, and may also guard against "manual surgery" cases where users put the system into an effectively broken state by fiddling with file attributes.

You can find info on the relevant windows APIs here:
* Setting directory compression state: https://learn.microsoft.com/en-us/windows/win32/fileio/creating-and-opening-files#file-attributes-and-directories
* Setting file compression state: https://learn.microsoft.com/en-us/windows/win32/fileio/compression-state

**Comment by eversinc33** [comment]
Very good points, I think this is the better approach. I will start implementing this in the new year and update this PR

**Comment by eversinc33** [comment]
Force pushed with the new approach.

image

Disables compression on both the directory as well as the blockchain file if set. If not, continues silently. Let me know what you think.

File: src/blockchain_db/lmdb/db_lmdb.cpp [hunk 1]
```diff
@@ -1347,6 +1350,16 @@ void BlockchainLMDB::open(const std::string& filename, const int db_flags)
     throw DB_ERROR("Database could not be opened");
   }
 
+#ifdef WIN32
+  // ensure NTFS compression is disabled on the directory and database file to avoid corruption of the blockchain 
+  if (boost::filesystem::exists(filename) && !disable_ntfs_compression(filename))
```
Comment (iamamyth) [inline src/blockchain_db/lmdb/db_lmdb.cpp:1355]: The earlier logic creates the directory (~line 1337), so you shouldn't need to check for existence (the extra check doesn't add race protection, and you don't need race protection).

File: src/blockchain_db/lmdb/db_lmdb.cpp [hunk 2]
```diff
@@ -1347,6 +1350,16 @@ void BlockchainLMDB::open(const std::string& filename, const int db_flags)
     throw DB_ERROR("Database could not be opened");
   }
 
+#ifdef WIN32
+  // ensure NTFS compression is disabled on the directory and database file to avoid corruption of the blockchain 
+  if (boost::filesystem::exists(filename) && !disable_ntfs_compression(filename)) 
+    LOG_PRINT_L0("Failed to disable NTFS compression on folder: " << filename << ". Error: " << ::GetLastError());
+  boost::filesystem::path datafile(filename);
+  datafile /= CRYPTONOTE_BLOCKCHAINDATA_FILENAME;
+  if (boost::filesystem::exists(datafile) && !disable_ntfs_compression(datafile))
```
Comment (iamamyth) [inline src/blockchain_db/lmdb/db_lmdb.cpp:1359]: I would touch the file so that it always exists, otherwise the daemon might have a compressed db on first launch. Also, if disabling compression fails, I'd throw a DB_ERROR.

File: src/blockchain_db/lmdb/db_lmdb.cpp [hunk 3]
```diff
@@ -1688,6 +1701,54 @@ std::string BlockchainLMDB::get_db_name() const
   return std::string("lmdb");
 }
 
+#ifdef WIN32
+bool BlockchainLMDB::disable_ntfs_compression(const boost::filesystem::path& filepath) const
```
Comment (iamamyth) [inline src/blockchain_db/lmdb/db_lmdb.cpp:1705]: Would make this `static` and move it to precede open.

**Comment by eversinc33** [comment]
Thank you again for the great feedback. Please see the latest commit.

File: src/blockchain_db/lmdb/db_lmdb.cpp [hunk 4]
```diff
@@ -1347,6 +1399,17 @@ void BlockchainLMDB::open(const std::string& filename, const int db_flags)
     throw DB_ERROR("Database could not be opened");
   }
 
+#ifdef WIN32
+  // ensure NTFS compression is disabled on the directory and database file to avoid corruption of the blockchain 
+  if (!disable_ntfs_compression(filename)) 
+    LOG_PRINT_L0("Failed to disable NTFS compression on folder: " << filename << ". Error: " << ::GetLastError());
+  boost::filesystem::path datafile(filename);
+  datafile /= CRYPTONOTE_BLOCKCHAINDATA_FILENAME;
+  boost::filesystem::ofstream(datafile.string()).close(); // touch the file to ensure it exists
```
Comment (iamamyth) [inline src/blockchain_db/lmdb/db_lmdb.cpp:1408]: I think you can simplify this to `ofstream(datafile)`, which avoids information loss from path->string conversion

**Comment by iamamyth** [comment]
A clarification on handling directory-level compression for other reviewers: One could argue that if the directory already exists, the program should preserve its compression attribute; in fact, I suggested as much in earlier comments. However, upon further consideration, I think it makes sense to choose the most intrusive option (always uncompress the directory) because:

1. It helps ensure consistent daemon behavior (as bug reports, and the Windows docs themselves, have illustrated, Windows filesystem compression is unreliable and non-transparent).
2. If the choice proves unworkable, a future PR can downgrade it, whereas starting with the least intrusive option (mixed compression modes) needlessly adds complexity.

**Comment by iamamyth** [comment]
Can you confirm that this modification runs normally on Windows and results in an an unencrypted data directory + db post-shutdown in the following startup scenarios?

* Empty data directory
    * Encrypted
    * Not encrypted
* Complete mainnet data directory
    * Encrypted
    * Not encrypted

File: src/blockchain_db/lmdb/db_lmdb.cpp (hunk 4 above)
Comment (eversinc33) [reply src/blockchain_db/lmdb/db_lmdb.cpp]: Fixed.

**Comment by iamamyth** [comment]
In most projects, I'd add tests for new behavior. Here, the tests ordinarily don't run on windows, so extra tests don't do much. If you want to add tests, you have two mutually exclusive options:

1. Add windows-only tests to tests/unit_test/blockchain_db.cpp (probably simpler and a technically reasonable choice).
2. Add windows-only functional tests to tests/functional_tests (reflects the regression/integration aspect of the tests).

**Review by iamamyth — APPROVED** [review]

**Comment by iamamyth** [comment]
There's a failing build: It looks like you need to explicitly add:
```
#include <boost/filesystem/fstream.hpp>
```

**Review by iamamyth — CHANGES_REQUESTED** [review]
There's a failing build. It looks like you need to explicitly add:
```
#include <boost/filesystem/fstream.hpp>
```

Everything else looks good. Thanks for your work on this issue!

**Comment by iamamyth** [comment]
One last thing: Probably a good idea to squash commits for merge.

**Review by iamamyth — APPROVED** [review]

**Comment by eversinc33** [comment]
Fixed and squashed. Thanks again for the good feedback!

**Review by selsta — APPROVED** [review]

**Comment by selsta** [comment]
Please also open this PR against `release-v0.18` branch.

**Comment by tobtoht** [comment]
Lots of extraneous whitespace in this patch.

**Comment by iamamyth** [comment]
> Lots of extraneous whitespace in this patch.

@tobtoht Was this posted on the wrong PR? I don't see any extraneous whitespace.

**Comment by selsta** [comment]
There are a lot of spaces at the end of some lines, would be good to fix before merging.

**Comment by nahuhh** [comment]
It seems to emulate codestyle from 1377-1402

**Comment by iamamyth** [comment]
Now I see the whitespace (using CLI), I think the github web UI got worse and made it really hard to see. @eversinc33 Can you remove the extraneous end-of-line whitespace and squash?

**Comment by eversinc33** [comment]
> Now I see the whitespace (using CLI), I think the github web UI got worse and made it really hard to see. @eversinc33 Can you remove the extraneous end-of-line whitespace and squash?

Sorry, not sure where that came from. Squashed and pushed

**Comment by eversinc33** [comment]
> Please also open this PR against `release-v0.18` branch.

See https://github.com/monero-project/monero/pull/9702

**Comment by selsta** [comment]
@eversinc33 Could you check again? This line for example still has whitespaces at the end of the line.

https://github.com/monero-project/monero/pull/9664/files#diff-94841b820d7dfb0ef2f631d635c246ea152fba2cf868b62a0dc084f04e9e2f6cR1364

**Comment by eversinc33** [comment]
Weird. I force pushed again, can you check now?

**Review by selsta — APPROVED** [review]
Looks good now.

**Review by 0xFFFC0000 — APPROVED** [review]
Thanks. LGTM.
