### PR TITLE
Fix describe_transfer for multiple txes in a txset

### LINKED ISSUE #7344: describe_transfer has incorrect output when multiple transactions are present
When `transfer_split` is used on a view-only wallet, it produces an unsigned transaction set. As implied by the term "set", this can comprise multiple transactions; this can occur when the required inputs mean that a single transaction would be too large. (Once #7322 is merged, it will also occur if more than 15 outputs are specified).

If this transaction set is inspected with `describe_transfer`, the response will contain multiple lists of recipients (one list per transaction) but the lists are incorrect. Specifically, the first list will correctly show the recipients from the first transaction, but the second list will contain the recipients from both the first and the second transactions, the third list contains recipients from the first, second, and third transactions, and so forth: each list contains the aggregated outputs from all transactions so far instead of just its own.

### PR DESCRIPTION
**Pull request by selsta**
Rebase of #7349

This ensures each list of recipients is only the recipients
for one transaction. It also adds a new field "summary"
that describes the txset as a whole.

Fixes #7344

### CODE REVIEW

File: src/wallet/wallet_rpc_server.cpp [hunk 1]
```diff
@@ -1374,29 +1377,45 @@ namespace tools
...
 
         desc.fee = desc.amount_in - desc.amount_out;
         desc.unlock_time = cd.unlock_time;
         desc.extra = epee::to_hex::string({cd.extra.data(), cd.extra.size()});
+
+        // Update summary items
+        res.summary.amount_in += desc.amount_in;
+        res.summary.amount_out += desc.amount_out;
+        res.summary.change_amount += desc.change_amount;
+        res.summary.fee += desc.fee;
```
Comment (moneromooo-monero) [inline src/wallet/wallet_rpc_server.cpp:1413]: Those aren't initialized at the top. It might be they always are in practice, but it seems best to init them at the start of the function.

**Review by moneromooo-monero — APPROVED** [review]
