### PR TITLE
monero-wallet-rpc: Prevent --password-file from being used with --wallet-dir

### LINKED ISSUE #7624: monero-wallet-rpc `--password-file` should be disallowed with `--wallet-dir` present
The following `monero-wallet-rpc` options are mutually exclusive: `--wallet-file`, `--generate-from-json` or `--wallet-dir`

From my understanding the option `--password-file` (used to provide a wallet's password) should be reserved to starting he RPC with `--wallet-file`. 
However, it is possible to start the RPC with `--wallet-dir` and `--password-file` - when trying to open a wallet with `open_wallet` this error is thrown:

```
2021-03-24 03:45:26.458	E THROW EXCEPTION: tools::error::wallet_internal_error
```

Note that it is irrelevant if the wallet which password file was provided is opened, or any other wallet, the error is always the same.

With both `--wallet-dir` and `--password-file` present, when creating a new wallet with `create_wallet` this error is thrown:

```
2021-03-24 03:59:29.128	E THROW EXCEPTION: tools::error::wallet_internal_error
2021-03-24 03:59:29.132	E [127.0.0.1:59048 INC] Failed to on_create_wallet(): can't specify more than one of --password and --password-file
```

Expected behavior: Fail early by restricting the `--password-file` option be disallowed if `--wallet-dir` is present.

### PR DESCRIPTION
**Pull request by DangerOnTheRanger**
This PR fixes #7624 by simply checking for the simultaneous presence of both `--password-file` and `--wallet-dir` when starting `monero-wallet-rpc`.

### CODE REVIEW

File: src/wallet/wallet_rpc_server.cpp [hunk 1]
```diff
@@ -4502,10 +4502,12 @@ class t_daemon
       const auto arg_wallet_file = wallet_args::arg_wallet_file();
       const auto arg_from_json = wallet_args::arg_generate_from_json();
       const auto arg_rpc_client_secret_key = wallet_args::arg_rpc_client_secret_key();
+	  const auto arg_password_file = wallet_args::arg_password_file();
 
       const auto wallet_file = command_line::get_arg(vm, arg_wallet_file);
       const auto from_json = command_line::get_arg(vm, arg_from_json);
       const auto wallet_dir = command_line::get_arg(vm, arg_wallet_dir);
+	  const auto password_file = command_line::get_arg(vm, arg_password_file);
```
Comment (moneromooo-monero) [inline src/wallet/wallet_rpc_server.cpp:4510]: You've just added tabs, which screws up indentation above. Please only add tabs to code that already uses tabs.

File: src/wallet/wallet2.cpp [hunk 2]
```diff
@@ -539,10 +541,10 @@ boost::optional<tools::password_container> get_password(const boost::program_opt
     return tools::password_container{command_line::get_arg(vm, opts.password)};
   }
 
-  if (command_line::has_arg(vm, opts.password_file))
+  if (!password_file.empty())
```
Comment (moneromooo-monero) [inline src/wallet/wallet2.cpp:544]: There is is_arg_defaulted, which does what I think you want here.

File: src/wallet/wallet_rpc_server.cpp (hunk 1 above)
Comment (DangerOnTheRanger) [reply src/wallet/wallet_rpc_server.cpp]: Sorry about that - fixed.

File: src/wallet/wallet2.cpp (hunk 2 above)
Comment (DangerOnTheRanger) [reply src/wallet/wallet2.cpp]: Thanks for pointing that out! I'll use that instead.

File: src/wallet/wallet2.cpp [hunk 3]
```diff
@@ -529,7 +530,8 @@ std::unique_ptr<tools::wallet2> make_basic(const boost::program_options::variabl
 
 boost::optional<tools::password_container> get_password(const boost::program_options::variables_map& vm, const options& opts, const std::function<boost::optional<tools::password_container>(const char*, bool)> &password_prompter, const bool verify)
 {
-  if (command_line::has_arg(vm, opts.password) && command_line::has_arg(vm, opts.password_file))
+  const auto password_file = command_line::get_arg(vm, opts.password_file);
+  if (command_line::has_arg(vm, opts.password) && !password_file.empty())
```
Comment (moneromooo-monero) [inline src/wallet/wallet2.cpp:534]: This one can also be is_arg_defaulted

Comment (DangerOnTheRanger) [reply src/wallet/wallet2.cpp]: Sorry about that, had missed that I had used `empty()` there.

File: src/wallet/wallet2.cpp [hunk 4]
```diff
@@ -539,10 +540,11 @@ boost::optional<tools::password_container> get_password(const boost::program_opt
     return tools::password_container{command_line::get_arg(vm, opts.password)};
   }
 
-  if (command_line::has_arg(vm, opts.password_file))
+  if (!command_line::is_arg_defaulted(vm, opts.password_file))
   {
     std::string password;
-    bool r = epee::file_io_utils::load_file_to_string(command_line::get_arg(vm, opts.password_file),
+	const auto password_file = command_line::get_arg(vm, opts.password_file);
```
Comment (selsta) [inline src/wallet/wallet2.cpp:546]: Indentation

File: src/wallet/wallet_args.cpp [hunk 5]
```diff
@@ -80,6 +80,10 @@ namespace wallet_args
   {
     return {"rpc-client-secret-key", wallet_args::tr("Set RPC client secret key for RPC payments"), ""};
   }
+  command_line::arg_descriptor<std::string> arg_password_file()
+  {
+	return {"password-file", wallet_args::tr("Wallet password file"), ""};
```
Comment (selsta) [inline src/wallet/wallet_args.cpp:85]: Indentation

File: src/wallet/wallet2.cpp (hunk 4 above)
Comment (DangerOnTheRanger) [reply src/wallet/wallet2.cpp]: Fixed, terribly sorry about all the indentation issues. I'll try to do a better job of noting what's being used for indentation in the future.

File: src/wallet/wallet_args.cpp (hunk 5 above)
Comment (DangerOnTheRanger) [reply src/wallet/wallet_args.cpp]: Fixed, sorry about that.

**Comment by selsta** [comment]
Ok please squash and afterwards it should be good

**Review by selsta — APPROVED** [review]
