### PR TITLE
fix on_battery_power for linux

### LINKED ISSUE #2143: Miner power supply
I'm getting an error when attempting to mine on linux:
```
uname -a
Linux fichte 4.11.6-3-ARCH #1 SMP PREEMPT Thu Jun 22 12:21:46 CEST 2017 x86_64 GNU/Linux
```

Error:

```
2017-07-02 16:27:15.516	    7f45517fa700	ERROR	miner	src/cryptonote_basic/miner.cpp:829	Couldn't find battery/power status file, can't determine if plugged in!
```
Seems like the issue comes from here: https://github.com/monero-project/monero/blob/421a6d0340527fe23c1b10cfd20769555afffb1b/src/cryptonote_basic/miner.cpp#L849. The paths to check battery status are hard coded.

Also, others appear to be having this issue: https://forum.getmonero.org/5/support/87704/mining-issue-on-linux and https://www.reddit.com/r/Monero/comments/61yy9s/essential_update_monero_01031_wolfram_warptangent/dfkczl0/

I can submit a PR to fix this if it is welcome.

### PR DESCRIPTION
**Pull request by mehtaphysical**
Fixes #2143

Includes fixes from PR #2144

### CODE REVIEW

File: src/cryptonote_basic/miner.cpp [hunk 1]
```diff
@@ -846,40 +846,81 @@ namespace cryptonote
...
+                  // We are only need to handle negative states right now
+
+                  if (is_plugged == boost::logic::indeterminate &&
+                      (boost::starts_with(power_supply_status, "Charging") || boost::starts_with(power_supply_status, "Full")))
+                  {
+                    is_plugged = boost::logic::tribool(true);
+                  }
+                  else
+                  {
+                    is_plugged = boost::logic::tribool(false);
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: Shouldn't this be indeterminate? E.g. if its not 'Charging' or 'Full' what other states can it be? From what I have read it can be discharging and unknown also at least.

File: src/cryptonote_basic/miner.cpp [hunk 2]
```diff
@@ -846,40 +846,81 @@ namespace cryptonote
...
+                if (boost::filesystem::is_regular_file(power_supply_status_path))
+                {
+                  std::string power_supply_status;
+                  epee::file_io_utils::load_file_to_string(power_supply_status_path, power_supply_status);
+
+                  // Possible status are Charging, Full, Discharging, Not Charging, and Unknown
+                  // We are only need to handle negative states right now
+
+                  if (is_plugged == boost::logic::indeterminate &&
+                      (boost::starts_with(power_supply_status, "Charging") || boost::starts_with(power_supply_status, "Full")))
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: What about the discharging state?

File: src/cryptonote_basic/miner.cpp [hunk 3]
```diff
@@ -846,40 +846,81 @@ namespace cryptonote
...
+      // Use the power_supply class http://lxr.linux.no/#linux+v4.10.1/Documentation/power/power_supply_class.txt
+      std::string power_supply_class_path = "/sys/class/power_supply";
 
-      for(const std::string& path : POWER_SUPPLY_STATUS_PATHS)
+      boost::tribool is_plugged = boost::logic::tribool(boost::logic::indeterminate);
+      if (boost::filesystem::is_directory(power_supply_class_path))
       {
-        if( epee::file_io_utils::is_file_exist(path) )
+        boost::filesystem::directory_iterator end_itr;
+        for (boost::filesystem::directory_iterator iter(power_supply_class_path); iter != end_itr; ++iter)
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: This project uses C++11 so this should be a range for loop ideally. Easier to read.

File: src/cryptonote_basic/miner.cpp [hunk 4]
```diff
@@ -846,40 +846,81 @@ namespace cryptonote
...
         {
-          power_supply_path = path;
-          break;
+          boost::filesystem::path power_supply_path = iter->path();
+          if (boost::filesystem::is_directory(iter->path()))
+          {
+            std::string power_supply_present;
+            epee::file_io_utils::load_file_to_string(power_supply_path.string() + "/present", power_supply_present);
+            if (!boost::starts_with(power_supply_present, "1")) {
+              LOG_PRINT_L4("Power supply not present at " << power_supply_path);
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: If power supply not _present_ should this not return true as must be running on battery?

File: src/cryptonote_basic/miner.cpp (hunk 2 above)
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: The moment this if block is entered, subsequent batteries can get into it because is_plugged will no longer be indeterminate.

File: src/cryptonote_basic/miner.cpp [hunk 5]
```diff
@@ -846,40 +846,81 @@ namespace cryptonote
...
-      if( power_stream.fail() )
-      {
-        LOG_ERROR("failed to open '" << power_supply_path << "'");
-        return boost::logic::tribool(boost::logic::indeterminate);;
+      if (is_plugged == boost::logic::indeterminate) {
+        LOG_ERROR("couldn't query power status from " << power_supply_class_path);
       }
-
-      return boost::logic::tribool( (power_stream.get() != '1') );
+      return is_plugged;
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: So if it's plugged in, why you are returning true for a function that is being queried as to whether being run on battery?

File: src/cryptonote_basic/miner.cpp (hunk 1 above)
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: My feeling is that if a battery status is Unknown, it is indeterminate.

File: src/cryptonote_basic/miner.cpp [hunk 6]
```diff
@@ -846,40 +846,81 @@ namespace cryptonote
...
+          {
+            std::string power_supply_present;
+            epee::file_io_utils::load_file_to_string(power_supply_path.string() + "/present", power_supply_present);
+            if (!boost::starts_with(power_supply_present, "1")) {
+              LOG_PRINT_L4("Power supply not present at " << power_supply_path);
+              continue;
+            }
+
+            std::string power_supply_type_path = power_supply_path.string() + "/type";
+            if (boost::filesystem::is_regular_file(power_supply_type_path))
```
Comment (vtnerd) [inline src/cryptonote_basic/miner.cpp]: `power_supply_path / "type"` (`operator/`) should do what you want and this the typical way of manipulating `boost::filesystem::path` instances. It does `\` for windows, etc. (although I guess that does not apply in this instance ...).

There is also `operator/=` if you want to modify the current path instance.

**Comment by jtgrassie** [comment]
I _think_ the logic needs to be like this:
```
// is on battery...
state = indeterminate
for each supply in power_supplies
    if supply is Mains and supply is online
        return false
    else if supply is Battery and state is indeterminate
        if supply is discharging
            state = true
        if supply is charging
            state = false
return state
```
Rational:

- A battery that is full doesn't give us a clear answer to the question as it simply may be recently charged, and the mains just been unplugged, thus is indeterminate.
- A battery that is charging is assumed the system has AC, e.g. not one battery charging another. Even though we make this assumption, we still allow the loop to find an official Mains supply.
- A battery that is discharging is assumed to be powering the system. Again the assumption allows the loop to continue to find a Mains supply.

File: src/cryptonote_basic/miner.cpp [hunk 7]
```diff
@@ -846,40 +846,81 @@ namespace cryptonote
...
-        "/sys/class/power_supply/ACAD/online",
-        "/sys/class/power_supply/AC/online",
-        "/sys/class/power_supply/AC0/online",
-        "/sys/class/power_supply/ADP0/online"
-      };
+      // Use the power_supply class http://lxr.linux.no/#linux+v4.10.1/Documentation/power/power_supply_class.txt
+      std::string power_supply_class_path = "/sys/class/power_supply";
 
-      for(const std::string& path : POWER_SUPPLY_STATUS_PATHS)
+      boost::tribool is_plugged = boost::logic::tribool(boost::logic::indeterminate);
```
Comment (vtnerd) [inline src/cryptonote_basic/miner.cpp]: I think a lot of the comments from @jtgrassie start here. The function is called `on_battery_power`, and the status variable for the loop is named `is_plugged`. These are opposing concepts. I think the logic would be easier to understand if they matched.

**Comment by jtgrassie** [comment]
@vtnerd 
> @jtgrassie there is no container to iterate over. 
Yes you are correct. This used to (in the previous PR that the author closed) was a vector. Now it's no longer a vector the iterator makes sense.

File: src/cryptonote_basic/miner.cpp (hunk 3 above)
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: Yep good spot. It used to be a vector but I see he changed it now to the direcotry_iterator.

File: src/cryptonote_basic/miner.cpp [hunk 8]
```diff
@@ -846,40 +846,81 @@ namespace cryptonote
...
+      if (boost::filesystem::is_directory(power_supply_class_path))
       {
-        if( epee::file_io_utils::is_file_exist(path) )
+        boost::filesystem::directory_iterator end_itr;
```
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: removed based on your range suggestion

File: src/cryptonote_basic/miner.cpp (hunk 3 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: yeah it was once a vector. that was removed because now we are iterating over all and not sorting

File: src/cryptonote_basic/miner.cpp (hunk 4 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: Oh battery is considered a "power supply" also.

File: src/cryptonote_basic/miner.cpp (hunk 1 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: makes sense. I'll push this change

File: src/cryptonote_basic/miner.cpp (hunk 5 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: that's a mistake

File: src/cryptonote_basic/miner.cpp (hunk 2 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: yeah this doesnt work. pushing a change

File: src/cryptonote_basic/miner.cpp (hunk 6 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: oh nice. updated

File: src/cryptonote_basic/miner.cpp [hunk 9]
```diff
@@ -846,40 +846,81 @@ namespace cryptonote
...
+        for (boost::filesystem::directory_iterator iter(power_supply_class_path); iter != end_itr; ++iter)
         {
-          power_supply_path = path;
-          break;
+          boost::filesystem::path power_supply_path = iter->path();
```
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: updated

File: src/cryptonote_basic/miner.cpp (hunk 8 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: nice thanks

File: src/cryptonote_basic/miner.cpp (hunk 7 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: hmm good call

**Comment by mehtaphysical** [comment]
@jtgrassie i think i did it a bit like you suggested i.e.

```
// is on battery...
state = indeterminate
for each supply in power_supplies
    if supply is Mains and supply is online
        return false
    else if supply is Battery and state is indeterminate
        if supply is discharging
            state = true
        if supply is charging
            state = false
return state
```

except there has to be another variable `is_charging` because I think if we ever see a discharging state we want to return false

**Comment by jtgrassie** [comment]
@mehtaphysical 

> i think i did it a bit like you suggested

Similar but not quite the same. I appreciate the logic is a little tricky but I think my [comment](https://github.com/monero-project/monero/pull/2147#issuecomment-313097938) has it correct.

> except there has to be another variable is_charging because I think if we ever see a discharging state we want to return true

No I don't think so. Remember you are just storing the state rather than returning instantly.

**Comment by mehtaphysical** [comment]
@jtgrassie in your comment though. lets say i see a discharging status first. state is then set to true. Later on another iteration i see a charging status state is then set to false. state is set to false even though there was a previous discharging status

File: src/cryptonote_basic/miner.cpp [hunk 10]
```diff
@@ -846,40 +846,89 @@ namespace cryptonote
...
+
+                  // Possible status are Charging, Full, Discharging, Not Charging, and Unknown
+                  // We are only need to handle negative states right now
+
+                  if (on_battery &&
+                      is_charging == boost::logic::indeterminate &&
+                      (boost::starts_with(power_supply_status, "Charging") || boost::starts_with(power_supply_status, "Full")))
+                  {
+                    on_battery = boost::logic::tribool(false);
+                    is_charging = boost::logic::tribool(true);
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: Status full does not mean it's charging from my understanding. It can be full for a short time with AC unplugged.
These extra variables are un-needed. Please see my comment describing the logic in pseudo-code as I think this whole function should be implemented like that as it handles all the cases.

File: src/cryptonote_basic/miner.cpp [hunk 11]
```diff
@@ -846,40 +846,89 @@ namespace cryptonote
...
+                  }
+                  else if (boost::starts_with(power_supply_status, "Discharging"))
+                  {
+                    on_battery = boost::logic::tribool(true);
+                    is_charging = boost::logic::tribool(false);
+                  }
+                  else
+                  {
+                    is_charging = boost::logic::tribool(false);
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: If it's not charging, full or discharging then it's indeterminate surely?

File: src/cryptonote_basic/miner.cpp (hunk 10 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: oh i see you have an indeterminate check also

File: src/cryptonote_basic/miner.cpp (hunk 11 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: is charging here is tracking the charging status. its not tracking the on_battery state

File: src/cryptonote_basic/miner.cpp [hunk 12]
```diff
@@ -846,40 +846,89 @@ namespace cryptonote
...
+        const boost::filesystem::directory_iterator end_itr;
+        for (boost::filesystem::directory_iterator iter(power_supply_class_path); iter != end_itr; ++iter)
         {
-          power_supply_path = path;
-          break;
+          const boost::filesystem::path & power_supply_path = iter->path();
+          if (boost::filesystem::is_directory(iter->path()))
+          {
+            std::string power_supply_present;
+            epee::file_io_utils::load_file_to_string((power_supply_path / "/present").string(), power_supply_present);
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: As you are now using the / operator I think you are supposed to drop the forward slash in "/present". The / operator add's in the correct path separator.

File: src/cryptonote_basic/miner.cpp [hunk 13]
```diff
@@ -846,40 +846,89 @@ namespace cryptonote
...
+            if (!boost::starts_with(power_supply_present, "1")) {
+              LOG_PRINT_L4("Power supply not present at " << power_supply_path);
+              continue;
+            }
+
+            boost::filesystem::path power_supply_type_path = power_supply_path / "/type";
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: As you are now using the / operator I think you are supposed to drop the forward slash in "/type". The / operator add's in the correct path separator.

File: src/cryptonote_basic/miner.cpp (hunk 12 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: cool thanks

**Comment by mehtaphysical** [comment]
so looking at your comment about the logic again i still think it doesn't work.

power_supply1 -> charging
power_supply2 -> unknown

in that case we return state = false. But we want to return state indeterminate since 1 power supply is unknown.

File: src/cryptonote_basic/miner.cpp [hunk 14]
```diff
@@ -846,40 +846,89 @@ namespace cryptonote
...
+            if (boost::filesystem::is_regular_file(power_supply_type_path))
+            {
+              std::string power_supply_type;
+              epee::file_io_utils::load_file_to_string(power_supply_type_path.string(), power_supply_type);
+
+              // If there is an AC adapter that's present and online we can break early
+              if (boost::starts_with(power_supply_type, "Mains"))
+              {
+                boost::filesystem::path power_supply_online_path = power_supply_path / "/online";
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: As you are now using the / operator I think you are supposed to drop the forward slash in "/online". The / operator add's in the correct path separator.

File: src/cryptonote_basic/miner.cpp [hunk 15]
```diff
@@ -846,40 +846,89 @@ namespace cryptonote
...
+                  }
+                  else
+                  {
+                    continue;
+                  }
+                }
+              }
+              else if (boost::starts_with(power_supply_type, "Battery"))
+              {
+                boost::filesystem::path power_supply_status_path = power_supply_path / "/status";
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: As you are now using the / operator I think you are supposed to drop the forward slash in "/status". The / operator add's in the correct path separator.

File: src/cryptonote_basic/miner.cpp (hunk 11 above)
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: In either case, if you implement my logic this has no bearing.

Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: But still, a battery that is not reporting as Full, Charging, or Discharging is indeterminate for it's charging state, not a definitive false.

**Comment by jtgrassie** [comment]
> so looking at your comment about the logic again i still think it doesn't work.
> 
> power_supply1 -> charging
> power_supply2 -> unknown
> 
> in that case we return state = false. But we want to return state indeterminate since 1 power supply is unknown.

I disagree. We do have a definitive state of Charging and thus it's on AC (one of the assumptions in this example case).

**Comment by mehtaphysical** [comment]
What if we have one discharging and one charging battery. What should be returned?

**Comment by jtgrassie** [comment]
@mehtaphysical 

> @jtgrassie in your comment though. lets say i see a discharging status first. state is then set to true. Later on another iteration i see a charging status state is then set to false. state is set to false even though there was a previous discharging status

But if you have charging happening you are on AC.

**Comment by jtgrassie** [comment]
> What if we have one discharging and one charging battery. What should be returned?

Charging, so on AC. I also am not sure this case can even exist. 2 batteries with one charging and one discharging?

**Comment by jtgrassie** [comment]
@mehtaphysical thanks for the apology, not required but appreciate it nonetheless.

**Comment by mehtaphysical** [comment]
im not sure if there can be a charging and discharging battery. I've seen people connect those backup batteries to their laptops.

anyways if we don't think that is possible, then your logic works.

We still need to consider what to do about Full i think

**Comment by jtgrassie** [comment]
@mehtaphysical 
> We still need to consider what to do about Full i think

That is accounted for as indeterminate (the default). A full battery does not in itself answer whether the system is running on batter or AC.

**Comment by mehtaphysical** [comment]
@jtgrassie if we do that, however, it leads to this really weird experience where my laptop will mine only until my battery is full. I think if we do that we should just always return indeterminate if the only power supply is a battery. its much less confusing for users that way.

**Comment by jtgrassie** [comment]
> if we do that, however, it leads to this really weird experience where my laptop will mine only until my battery is full. 

Can you elaborate how that state would happen please?

> I think if we do that we should just always return indeterminate if the only power supply is a battery. its much less confusing for users that way.

But with my logic, it covers this use case and would return indeterminate. e.g. if you only had one power source, a battery, and it was reporting as Full, my logic would yield a return of indeterminate.

**Comment by mehtaphysical** [comment]
> Can you elaborate how that state would happen please?

This would happen whenever my laptop is plugged in. If it is ever fully charged it will stop mining. The status will change from `Charging` to `Full` and so indeterminate will start being returned.

> But with my logic, it covers this use case and would return indeterminate. e.g. if you only had one power source, a battery, and it was reporting as Full, my logic would yield a return of indeterminate.

My point is that we should return indeterminate anytime the only power supply is battery if we consider `Full` as an indeterminate state. Its weird that it is only considered on AC when the battery is not full.

**Comment by jtgrassie** [comment]
> This would happen whenever my laptop is plugged in. If it is ever fully charged it will stop mining. The status will change from Charging to Full and so indeterminate will start being returned.

Are you saying that your laptop, when plugged in, does not have a Mains power source? I can see AC* and BAT* in `/sys/class/power_supply`.

> My point is that we should return indeterminate anytime the only power supply is battery if we consider Full as an indeterminate state. 

Sorry but I just don't follow your logic here.

> Its weird that it is only considered on AC when the battery is not full.

But that's not the case though. It can be considered on AC if It has a Mains online or has a battery that is status charging.

If you are saying your laptop, when plugged in, has no /sys/class/power_supply/AC* then I can see an issue. Your battery would be Charging then Full. If this is the case, then it's a simple modification to the logic. Regard Full as not running on battery, so return false. I think this is OK because if it really is running on battery, not mains, it wont stay Full for long.

So updated:
```// is on battery...
state = indeterminate
for each supply in power_supplies
    if supply is Mains and supply is online
        return false
    else if supply is Battery and state is indeterminate
        if supply is discharging
            state = true
        if supply is charging or status is full
            state = false
return state
```

**Comment by mehtaphysical** [comment]
@jtgrassie yes that is precisely my point.

```
▶ ls /sys/class/power_supply             
BAT0

~                                                                                                                                                                                                                   
▶ cat /sys/class/power_supply/BAT0/status
Charging
```

If it says full that should mean that it is on AC power. So if you look at the code that is how it is.

**Comment by jtgrassie** [comment]
@mehtaphysical if you are not seeing AC in the /sys/class/power_supply it's likely you do not have the kernel module loaded:
https://wiki.archlinux.org/index.php/ACPI_modules

Looks like you might have loaded battery.ko.gz but not ac.ko.gz.

File: src/cryptonote_basic/miner.cpp [hunk 16]
```diff
@@ -846,40 +846,77 @@ namespace cryptonote
...
+        for (boost::filesystem::directory_iterator iter(power_supply_class_path); iter != end_itr; ++iter)
         {
-          power_supply_path = path;
-          break;
+          const boost::filesystem::path & power_supply_path = iter->path();
+          if (boost::filesystem::is_directory(iter->path()))
+          {
+            std::string power_supply_present;
+            epee::file_io_utils::load_file_to_string((power_supply_path / "present").string(), power_supply_present);
+            if (!boost::starts_with(power_supply_present, "1")) {
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: Minor point but missing newline between ) and {

File: src/cryptonote_basic/miner.cpp [hunk 17]
```diff
@@ -846,40 +846,77 @@ namespace cryptonote
...
-        LOG_ERROR("Couldn't find battery/power status file, can't determine if plugged in!");
-        return boost::logic::tribool(boost::logic::indeterminate);;
-      }
-
-      std::ifstream power_stream(power_supply_path);
-      if( power_stream.fail() )
-      {
-        LOG_ERROR("failed to open '" << power_supply_path << "'");
-        return boost::logic::tribool(boost::logic::indeterminate);;
+      if (on_battery == boost::logic::indeterminate) {
```
Comment (jtgrassie) [inline src/cryptonote_basic/miner.cpp]: Minor point but missing newline between ) and {

**Comment by mehtaphysical** [comment]
```
▶ ls /usr/lib/modules/$(uname -r)/kernel/drivers/acpi   
ac.ko.gz             acpi_extlog.ko.gz  acpi_pad.ko.gz  battery.ko.gz  custom_method.ko.gz  ec_sys.ko.gz  nfit         sbs.ko.gz      video.ko.gz
acpi_configfs.ko.gz  acpi_ipmi.ko.gz    apei            button.ko.gz   dptf                 fan.ko.gz     sbshc.ko.gz  thermal.ko.gz
```

File: src/cryptonote_basic/miner.cpp (hunk 16 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: thanks fixed

File: src/cryptonote_basic/miner.cpp (hunk 17 above)
Comment (mehtaphysical) [inline src/cryptonote_basic/miner.cpp]: thanks fixed

**Comment by jtgrassie** [comment]
@mehtaphysical have you modprobed ac.ko.gz though??

**Comment by jtgrassie** [comment]
Also check your dmesg output to ensure the ac module has loaded. Not that it really matters as I think it's fine to assume Full is on AC. Because like I said earlier, if it's not truly on AC, it will be Discharging pretty soon after!

**Comment by mehtaphysical** [comment]
```
▶ lsmod | grep -e "^ac "
ac                     16384  0
```

**Comment by jtgrassie** [comment]
Well that's very odd! If you have the ac acpi module loaded you should definitely have an AC* entry in /sys/class/power_supply. Anyway we are going slightly off topic and your machine specific. Returning as if on AC when Full is fine IMHO, per previous comment.

**Comment by mehtaphysical** [comment]
but yeah i think its fine to assume Full is on ac. Other people do this as well. Like android for example https://developer.android.com/training/monitoring-device-state/battery-monitoring.html

**Comment by jtgrassie** [comment]
We got there in the end ;)

**Comment by mehtaphysical** [comment]
yup! thanks for all the help clarifying everything :).

**Comment by mehtaphysical** [comment]
i added a little bit better error handling because i started seeing a stacktrace when this runs in detached mode. 

I'll try to fix that, but i'll leave a comment on the line in case anyone has an idea

**Comment by jtgrassie** [comment]
Posting the stacktrace would be more useful. Also, the previous code (on master) has a check on the file stream. I guess there could be an issue with the file changing while it's being read. You need to return indeterminate if there are errors while reading these files and let the next sweep try and get the status.

**Comment by mehtaphysical** [comment]
here's the stacktrace
```
2017-07-06 05:21:57.821	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:119	Exception: std::ios_base::failure[abi:cxx11]
2017-07-06 05:21:57.821	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:120	Unwound call stack:
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [1] /usr/bin/monerod:__cxa_throw+0xf2 [0x747912]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [2] /usr/lib/libstdc++.so.6:std::__throw_ios_failure(char const*)+0x63 [0x7f1c37c38a83]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [3] /usr/lib/libstdc++.so.6+0xf921d [0x7f1c37c7721d]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [4] /usr/lib/libstdc++.so.6:std::istream::read(char*, long)+0x99 [0x7f1c37c7ae79]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [5] /usr/bin/monerod:epee::file_io_utils::load_file_to_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)+0x32a [0x7a3bea]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [6] /usr/bin/monerod:cryptonote::miner::on_battery_power()+0x32f [0x7bc5af]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [7] /usr/bin/monerod:cryptonote::miner::background_worker_thread()+0x1df [0x7bd10f]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [8] /usr/lib/libboost_thread.so.1.64.0+0x1340d [0x7f1c385ff40d]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [9] /usr/lib/libpthread.so.0+0x7297 [0x7f1c3743e297]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [10] /usr/lib/libc.so.6:clone+0x3f [0x7f1c3717f1ef]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	
2017-07-06 05:21:57.824	    7f13e1b3b700	WARN 	default	contrib/epee/include/file_io_utils.h:91	/sys/class/power_supply/BAT0/type
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:119	Exception: std::ios_base::failure[abi:cxx11]
2017-07-06 05:21:57.824	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:120	Unwound call stack:
2017-07-06 05:21:57.827	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [1] /usr/bin/monerod:__cxa_throw+0xf2 [0x747912]
2017-07-06 05:21:57.827	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [2] /usr/lib/libstdc++.so.6:std::__throw_ios_failure(char const*)+0x63 [0x7f1c37c38a83]
2017-07-06 05:21:57.827	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [3] /usr/lib/libstdc++.so.6+0xf921d [0x7f1c37c7721d]
2017-07-06 05:21:57.827	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [4] /usr/lib/libstdc++.so.6:std::istream::read(char*, long)+0x99 [0x7f1c37c7ae79]
2017-07-06 05:21:57.828	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [5] /usr/bin/monerod:epee::file_io_utils::load_file_to_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)+0x32a [0x7a3bea]
2017-07-06 05:21:57.828	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [6] /usr/bin/monerod:cryptonote::miner::on_battery_power()+0x69e [0x7bc91e]
2017-07-06 05:21:57.828	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [7] /usr/bin/monerod:cryptonote::miner::background_worker_thread()+0x1df [0x7bd10f]
2017-07-06 05:21:57.828	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [8] /usr/lib/libboost_thread.so.1.64.0+0x1340d [0x7f1c385ff40d]
2017-07-06 05:21:57.828	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [9] /usr/lib/libpthread.so.0+0x7297 [0x7f1c3743e297]
2017-07-06 05:21:57.828	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [10] /usr/lib/libc.so.6:clone+0x3f [0x7f1c3717f1ef]
2017-07-06 05:21:57.828	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	
2017-07-06 05:21:57.828	    7f13e1b3b700	WARN 	default	contrib/epee/include/file_io_utils.h:91	/sys/class/power_supply/BAT0/status
2017-07-06 05:21:57.828	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:119	Exception: std::ios_base::failure[abi:cxx11]
2017-07-06 05:21:57.828	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:120	Unwound call stack:
2017-07-06 05:21:57.830	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [1] /usr/bin/monerod:__cxa_throw+0xf2 [0x747912]
2017-07-06 05:21:57.830	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [2] /usr/lib/libstdc++.so.6:std::__throw_ios_failure(char const*)+0x63 [0x7f1c37c38a83]
2017-07-06 05:21:57.831	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [3] /usr/lib/libstdc++.so.6+0xf921d [0x7f1c37c7721d]
2017-07-06 05:21:57.831	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [4] /usr/lib/libstdc++.so.6:std::istream::read(char*, long)+0x99 [0x7f1c37c7ae79]
2017-07-06 05:21:57.831	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [5] /usr/bin/monerod:epee::file_io_utils::load_file_to_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)+0x32a [0x7a3bea]
2017-07-06 05:21:57.831	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [6] /usr/bin/monerod:cryptonote::miner::on_battery_power()+0x825 [0x7bcaa5]
2017-07-06 05:21:57.831	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [7] /usr/bin/monerod:cryptonote::miner::background_worker_thread()+0x1df [0x7bd10f]
2017-07-06 05:21:57.831	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [8] /usr/lib/libboost_thread.so.1.64.0+0x1340d [0x7f1c385ff40d]
2017-07-06 05:21:57.831	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [9] /usr/lib/libpthread.so.0+0x7297 [0x7f1c3743e297]
2017-07-06 05:21:57.831	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [10] /usr/lib/libc.so.6:clone+0x3f [0x7f1c3717f1ef]
2017-07-06 05:21:57.831	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	
^C

~                                                                                                      ⍉
▶ tail -f /var/log/monero/monero.log
2017-07-06 05:33:26.778	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [6] /usr/lib/libboost_thread.so.1.64.0+0x1340d [0x7f1c385ff40d]
2017-07-06 05:33:26.778	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [7] /usr/lib/libpthread.so.0+0x7297 [0x7f1c3743e297]
2017-07-06 05:33:26.778	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	    [8] /usr/lib/libc.so.6:clone+0x3f [0x7f1c3717f1ef]
2017-07-06 05:33:26.778	    7f13e1b3b700	INFO 	stacktrace	src/common/stack_trace.cpp:158	
```
The code actually still works even though the stacktrace is appearing. What it is, i think, is `fstream.tellg()` is returning an inaccurate size. The file size is 4KB, so tellg() is returning 4096. This makes `target_str.size() == 4096`. However, the actual text in the file is much less than that.

**Comment by mehtaphysical** [comment]
ok i updated this to fix the read error i was getting. I'll keep the commits for now so the diff is more clear. If it looks good to you @jtgrassie i'll squash them.

**Comment by jtgrassie** [comment]
> What it is, i think, is fstream.tellg() is returning an inaccurate size. The file size is 4KB, so tellg() is returning 4096. This makes target_str.size() == 4096. However, the actual text in the file is much less than that.

No it's because the file is being updated while being read. tellg returns the correct size, not 4k. 

Now you are checking if the stream.fail() should be fine.

**Comment by jtgrassie** [comment]
>  If it looks good to you @jtgrassie i'll squash them.

squash away yes.

**Comment by NanoAkron** [comment]
This discussion sounds like someone needs to write a nice portable library to detect charging for all sorts of projects...
